### ISSUE TITLE
Unclear how to assign blockers

### ISSUE THREAD

**Issue by lacker** [andrewljohnson/CardAI#17]
<img width="550" alt="screen shot 2018-05-04 at 9 18 28 pm" src="https://user-images.githubusercontent.com/106475/39659599-bccf8254-4fe0-11e8-9c6b-90f4b2450736.png">

**Comment by lacker** [comment]
I don't see why there are 7 options, either - I only have one untapped creature and they have one (I think?) attacking creature.

**Comment by andrewljohnson** [comment]
shoulda done printed board here, but anyways... I just made this clearer... please pull and try again
